# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Global Headquarters Web Development
email: levigrantrose@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Global Headquarters Web Development creates websites, blogs, web applications and e-commerce sites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ghqwebdevelopment" # the base hostname & protocol for your site
github_username:  Levigrantrose

# Build settings
markdown: kramdown
